# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'ReachabilitySwift'
pod 'RealmSwift', '~>10'
pod 'Moya'
pod 'Kingfisher'

  # Pods for PokemonApp

  target 'PokemonAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokemonAppUITests' do
    # Pods for testing
  end

end
